[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sn_telmodel"
version="1.0.2"
requires-python = ">=3.5"

authors = [
  {name = "Philippe Gris", email = "philippe.gris@clermont.in2p3.fr"},
]
maintainers = [
  {name = "Philippe Gris", email = "philippe.gris@clermont.in2p3.fr"}
]
description = "Set of tools for telescope model'"
readme = "README.rst"
classifiers = ["Programming Language :: Python",]

[tool.setuptools.packages.find]
where = ["."]
include = ["sn_telmodel*"]

[project.urls]
Homepage = "http://github.com/lsstdesc/sn_telmodel"
Repository = "https://github.com/lsstdesc/sn_telmodel"